/*
 *    ____  _ _ _
 *   | __ )(_) | |_
 *   |  _ \| | | __|
 *   | |_) | | | |_
 *   |____/|_|_|\__|
 *
 *   Bilt POS SDK
 *
 *   This file is auto-generated from the Nexo Sale to POI v3.0 JSON Schema.
 *   Do not modify manually — re-run code generation instead.
 */
package com.bilt.pos.nexo.model;

import com.fasterxml.jackson.annotation.*;

/**
 * Result of a single transaction performed without the Sale System, returned in a Batch
 * response.
 */
public class PerformedTransaction {
    private LoyaltyResult[] loyaltyResult;
    private PaymentResult paymentResult;
    private POIData poiData;
    private Response response;
    private Double reversedAmount;
    private SaleData saleData;

    @JsonProperty("LoyaltyResult")
    public LoyaltyResult[] getLoyaltyResult() { return loyaltyResult; }
    @JsonProperty("LoyaltyResult")
    public void setLoyaltyResult(LoyaltyResult[] value) { this.loyaltyResult = value; }

    @JsonProperty("PaymentResult")
    public PaymentResult getPaymentResult() { return paymentResult; }
    @JsonProperty("PaymentResult")
    public void setPaymentResult(PaymentResult value) { this.paymentResult = value; }

    @JsonProperty("POIData")
    public POIData getPoiData() { return poiData; }
    @JsonProperty("POIData")
    public void setPoiData(POIData value) { this.poiData = value; }

    @JsonProperty("Response")
    public Response getResponse() { return response; }
    @JsonProperty("Response")
    public void setResponse(Response value) { this.response = value; }

    /**
     * Amount reversed. Mandatory when this PerformedTransaction is the result of a reversal.
     */
    @JsonProperty("ReversedAmount")
    public Double getReversedAmount() { return reversedAmount; }
    @JsonProperty("ReversedAmount")
    public void setReversedAmount(Double value) { this.reversedAmount = value; }

    /**
     * Sale transaction identification. Present only when the transaction was generated by the
     * Sale System.
     */
    @JsonProperty("SaleData")
    public SaleData getSaleData() { return saleData; }
    @JsonProperty("SaleData")
    public void setSaleData(SaleData value) { this.saleData = value; }
    
    public static Builder builder() { return new Builder(); }
    
    public static final class Builder {
        private LoyaltyResult[] loyaltyResult;
        private PaymentResult paymentResult;
        private POIData poiData;
        private Response response;
        private Double reversedAmount;
        private SaleData saleData;
        
        private Builder() {}
        
        public Builder loyaltyResult(LoyaltyResult[] loyaltyResult) {
            this.loyaltyResult = loyaltyResult;
            return this;
        }
        
        public Builder paymentResult(PaymentResult paymentResult) {
            this.paymentResult = paymentResult;
            return this;
        }
        
        public Builder poiData(POIData poiData) {
            this.poiData = poiData;
            return this;
        }
        
        public Builder response(Response response) {
            this.response = response;
            return this;
        }
        
        public Builder reversedAmount(Double reversedAmount) {
            this.reversedAmount = reversedAmount;
            return this;
        }
        
        public Builder saleData(SaleData saleData) {
            this.saleData = saleData;
            return this;
        }
        
        public PerformedTransaction build() {
            PerformedTransaction result = new PerformedTransaction();
            result.setLoyaltyResult(this.loyaltyResult);
            result.setPaymentResult(this.paymentResult);
            result.setPoiData(this.poiData);
            result.setResponse(this.response);
            result.setReversedAmount(this.reversedAmount);
            result.setSaleData(this.saleData);
            return result;
        }
    }
}
