/*
 *    ____  _ _ _
 *   | __ )(_) | |_
 *   |  _ \| | | __|
 *   | |_) | | | |_
 *   |____/|_|_|\__|
 *
 *   Bilt POS SDK
 *
 *   This file is auto-generated from the Nexo Sale to POI v3.0 JSON Schema.
 *   Do not modify manually — re-run code generation instead.
 */
package com.bilt.pos.nexo.model;

import com.fasterxml.jackson.annotation.*;

/**
 * Data associated with the Sale System context for a transaction, including transaction
 * identification and terminal characteristics.
 *
 * Sale transaction identification. Present only when the transaction was generated by the
 * Sale System.
 */
public class SaleData {
    private CustomerOrderReqType[] customerOrderReq;
    private String operatorID;
    private String operatorLanguage;
    private String saleReferenceID;
    private SaleTerminalData saleTerminalData;
    private String saleToAcquirerData;
    private String saleToIssuerData;
    private String saleToPOIData;
    private TransactionIdentificationType saleTransactionID;
    private String shiftNumber;
    private String statementReference;
    private TokenRequestedTypeEnum tokenRequestedType;

    @JsonProperty("CustomerOrderReq")
    public CustomerOrderReqType[] getCustomerOrderReq() { return customerOrderReq; }
    @JsonProperty("CustomerOrderReq")
    public void setCustomerOrderReq(CustomerOrderReqType[] value) { this.customerOrderReq = value; }

    /**
     * Identification of the Cashier or Operator. Sent when different from the Login value.
     */
    @JsonProperty("OperatorID")
    public String getOperatorID() { return operatorID; }
    @JsonProperty("OperatorID")
    public void setOperatorID(String value) { this.operatorID = value; }

    /**
     * Language of the Cashier. Sent when different from the Login value.
     */
    @JsonProperty("OperatorLanguage")
    public String getOperatorLanguage() { return operatorLanguage; }
    @JsonProperty("OperatorLanguage")
    public void setOperatorLanguage(String value) { this.operatorLanguage = value; }

    /**
     * Global Sale identification for a sequence of related POI transactions, e.g. for
     * reservation or customer orders.
     */
    @JsonProperty("SaleReferenceID")
    public String getSaleReferenceID() { return saleReferenceID; }
    @JsonProperty("SaleReferenceID")
    public void setSaleReferenceID(String value) { this.saleReferenceID = value; }

    @JsonProperty("SaleTerminalData")
    public SaleTerminalData getSaleTerminalData() { return saleTerminalData; }
    @JsonProperty("SaleTerminalData")
    public void setSaleTerminalData(SaleTerminalData value) { this.saleTerminalData = value; }

    /**
     * Sale information forwarded unchanged to the Acquirer.
     */
    @JsonProperty("SaleToAcquirerData")
    public String getSaleToAcquirerData() { return saleToAcquirerData; }
    @JsonProperty("SaleToAcquirerData")
    public void setSaleToAcquirerData(String value) { this.saleToAcquirerData = value; }

    /**
     * Sale information forwarded unchanged to the Issuer via the Acquirer.
     */
    @JsonProperty("SaleToIssuerData")
    public String getSaleToIssuerData() { return saleToIssuerData; }
    @JsonProperty("SaleToIssuerData")
    public void setSaleToIssuerData(String value) { this.saleToIssuerData = value; }

    /**
     * Sale information stored by the POI with the transaction but not interpreted.
     */
    @JsonProperty("SaleToPOIData")
    public String getSaleToPOIData() { return saleToPOIData; }
    @JsonProperty("SaleToPOIData")
    public void setSaleToPOIData(String value) { this.saleToPOIData = value; }

    /**
     * Unique identification of the transaction for the Sale System (e.g. ticket number).
     */
    @JsonProperty("SaleTransactionID")
    public TransactionIdentificationType getSaleTransactionID() { return saleTransactionID; }
    @JsonProperty("SaleTransactionID")
    public void setSaleTransactionID(TransactionIdentificationType value) { this.saleTransactionID = value; }

    /**
     * Shift number. Sent when different from the Login value.
     */
    @JsonProperty("ShiftNumber")
    public String getShiftNumber() { return shiftNumber; }
    @JsonProperty("ShiftNumber")
    public void setShiftNumber(String value) { this.shiftNumber = value; }

    /**
     * Reference label to print on the bank statement.
     */
    @JsonProperty("StatementReference")
    public String getStatementReference() { return statementReference; }
    @JsonProperty("StatementReference")
    public void setStatementReference(String value) { this.statementReference = value; }

    @JsonProperty("TokenRequestedType")
    public TokenRequestedTypeEnum getTokenRequestedType() { return tokenRequestedType; }
    @JsonProperty("TokenRequestedType")
    public void setTokenRequestedType(TokenRequestedTypeEnum value) { this.tokenRequestedType = value; }
    
    public static Builder builder() { return new Builder(); }
    
    public static final class Builder {
        private CustomerOrderReqType[] customerOrderReq;
        private String operatorID;
        private String operatorLanguage;
        private String saleReferenceID;
        private SaleTerminalData saleTerminalData;
        private String saleToAcquirerData;
        private String saleToIssuerData;
        private String saleToPOIData;
        private TransactionIdentificationType saleTransactionID;
        private String shiftNumber;
        private String statementReference;
        private TokenRequestedTypeEnum tokenRequestedType;
        
        private Builder() {}
        
        public Builder customerOrderReq(CustomerOrderReqType[] customerOrderReq) {
            this.customerOrderReq = customerOrderReq;
            return this;
        }
        
        public Builder operatorID(String operatorID) {
            this.operatorID = operatorID;
            return this;
        }
        
        public Builder operatorLanguage(String operatorLanguage) {
            this.operatorLanguage = operatorLanguage;
            return this;
        }
        
        public Builder saleReferenceID(String saleReferenceID) {
            this.saleReferenceID = saleReferenceID;
            return this;
        }
        
        public Builder saleTerminalData(SaleTerminalData saleTerminalData) {
            this.saleTerminalData = saleTerminalData;
            return this;
        }
        
        public Builder saleToAcquirerData(String saleToAcquirerData) {
            this.saleToAcquirerData = saleToAcquirerData;
            return this;
        }
        
        public Builder saleToIssuerData(String saleToIssuerData) {
            this.saleToIssuerData = saleToIssuerData;
            return this;
        }
        
        public Builder saleToPOIData(String saleToPOIData) {
            this.saleToPOIData = saleToPOIData;
            return this;
        }
        
        public Builder saleTransactionID(TransactionIdentificationType saleTransactionID) {
            this.saleTransactionID = saleTransactionID;
            return this;
        }
        
        public Builder shiftNumber(String shiftNumber) {
            this.shiftNumber = shiftNumber;
            return this;
        }
        
        public Builder statementReference(String statementReference) {
            this.statementReference = statementReference;
            return this;
        }
        
        public Builder tokenRequestedType(TokenRequestedTypeEnum tokenRequestedType) {
            this.tokenRequestedType = tokenRequestedType;
            return this;
        }
        
        public SaleData build() {
            SaleData result = new SaleData();
            result.setCustomerOrderReq(this.customerOrderReq);
            result.setOperatorID(this.operatorID);
            result.setOperatorLanguage(this.operatorLanguage);
            result.setSaleReferenceID(this.saleReferenceID);
            result.setSaleTerminalData(this.saleTerminalData);
            result.setSaleToAcquirerData(this.saleToAcquirerData);
            result.setSaleToIssuerData(this.saleToIssuerData);
            result.setSaleToPOIData(this.saleToPOIData);
            result.setSaleTransactionID(this.saleTransactionID);
            result.setShiftNumber(this.shiftNumber);
            result.setStatementReference(this.statementReference);
            result.setTokenRequestedType(this.tokenRequestedType);
            return result;
        }
    }
}
